from .audit import audit_local_data_assets
from .first_batch import (
    apply_malf_snapshot_manual_review_verdicts,
    apply_qualification_record_draft_manual_verdicts,
    audit_add_on_price_limit_shortlist_time_alignment,
    audit_formal_front_filter_review_package,
    audit_first_batch_sample_coverage,
    audit_institution_rule_definition_readiness_when_explicitly_requested,
    audit_trading_layer_read_gate_contract_when_explicitly_requested,
    audit_trading_layer_readiness_for_candidate_table_when_explicitly_requested,
    build_first_batch_sample_package,
    build_default_add_on_price_limit_shortlist_malf_research_prep,
    build_shortlist_malf_research_prep,
    build_shortlist_sample_package,
    default_add_on_price_limit_shortlist_sample_entries,
    materialize_default_add_on_price_limit_core_malf_research_bundle,
    prepare_malf_snapshot_draft_review,
    prepare_candidate_table_update_audit_when_explicitly_requested,
    prepare_formal_front_filter_review_package,
    prepare_formal_qualification_record_persistence_package_when_explicitly_requested,
    prepare_formal_qualification_record_write_audit,
    prepare_qualification_record_draft_review,
    review_add_on_price_limit_post_label_daily_malf_structure,
    review_add_on_price_limit_post_label_intraday_reopen,
    rescreen_add_on_price_limit_post_industry_window,
    update_candidate_table_from_staged_qualification_records_when_explicitly_requested,
    write_candidate_table_to_formal_data_root_when_explicitly_confirmed,
    write_qualification_records_to_staging_when_explicitly_requested,
)
from .readers import (
    build_minimal_read_report,
    inspect_duckdb_assets,
    probe_pytdx_reader,
    read_daily_bars,
    read_intraday_range,
    read_sector_membership,
    read_symbol_master,
    read_trading_calendar,
)
from .price_limit_sample_pool import (
    screen_pullback_add_price_limit_candidates,
    screen_pullback_add_price_limit_candidates_with_intraday,
    shortlist_core_malf_snapshot_candidates,
    shortlist_formal_pressure_adjust_review_candidates,
    shortlist_pullback_add_pressure_adjust_candidates,
)

__all__ = [
    "audit_local_data_assets",
    "apply_malf_snapshot_manual_review_verdicts",
    "apply_qualification_record_draft_manual_verdicts",
    "audit_add_on_price_limit_shortlist_time_alignment",
    "audit_formal_front_filter_review_package",
    "audit_first_batch_sample_coverage",
    "audit_institution_rule_definition_readiness_when_explicitly_requested",
    "audit_trading_layer_read_gate_contract_when_explicitly_requested",
    "audit_trading_layer_readiness_for_candidate_table_when_explicitly_requested",
    "build_first_batch_sample_package",
    "build_default_add_on_price_limit_shortlist_malf_research_prep",
    "build_shortlist_malf_research_prep",
    "build_shortlist_sample_package",
    "default_add_on_price_limit_shortlist_sample_entries",
    "materialize_default_add_on_price_limit_core_malf_research_bundle",
    "prepare_malf_snapshot_draft_review",
    "prepare_candidate_table_update_audit_when_explicitly_requested",
    "prepare_formal_front_filter_review_package",
    "prepare_formal_qualification_record_persistence_package_when_explicitly_requested",
    "prepare_formal_qualification_record_write_audit",
    "prepare_qualification_record_draft_review",
    "review_add_on_price_limit_post_label_daily_malf_structure",
    "review_add_on_price_limit_post_label_intraday_reopen",
    "rescreen_add_on_price_limit_post_industry_window",
    "update_candidate_table_from_staged_qualification_records_when_explicitly_requested",
    "write_candidate_table_to_formal_data_root_when_explicitly_confirmed",
    "write_qualification_records_to_staging_when_explicitly_requested",
    "build_minimal_institution_fact_package",
    "build_minimal_read_report",
    "inspect_duckdb_assets",
    "probe_pytdx_reader",
    "read_daily_bars",
    "read_intraday_range",
    "screen_pullback_add_price_limit_candidates",
    "screen_pullback_add_price_limit_candidates_with_intraday",
    "shortlist_core_malf_snapshot_candidates",
    "shortlist_formal_pressure_adjust_review_candidates",
    "shortlist_pullback_add_pressure_adjust_candidates",
    "read_sector_membership",
    "read_symbol_master",
    "read_trading_calendar",
]


def __getattr__(name: str):
    if name == "build_minimal_institution_fact_package":
        from .institution_facts import build_minimal_institution_fact_package

        return build_minimal_institution_fact_package
    raise AttributeError(name)
