from __future__ import annotations

import json
from typing import Any



FORBIDDEN_OUTPUT_FIELDS = {
    "buy_signal",
    "sell_signal",
    "trade_accept",
    "target_position",
    "ashare_t1_action",
    "position_size",
    "center_position",
}

CANDIDATE_TABLE_GATE_FIELDS = [
    "record_consistency",
    "rhythm_meaning",
    "tachibana_applicability",
    "qualification_rule_id",
    "boundary_warning",
    "evidence_level",
]

BACKTEST_INPUT_FORBIDDEN_FIELDS = {
    "signal_decision",
    "trade_accept",
    "trade_reject",
    "trade_defer",
    "signal_decision_from_rhythm",
    "trade_accept_from_meaningful",
    "trade_reject_from_not_meaningful",
    "backtest_gate_by_rhythm_only",
    "prediction_direction",
    "target_position_from_malf",
    "center_position_from_malf",
    "lock_confirmed_by_malf",
    "structure_strength_by_size",
}

METHOD_ACTIONS = {
    "trend_probe_entry",
    "trend_confirmation_add",
    "pullback_entry",
    "pullback_add",
    "distribution_reduce",
    "exit_on_rhythm_failure",
    "reversal_flip",
    "inventory_rebalance",
    "wait_no_action",
}

METHOD_STATUSES = {"observed", "inferred", "hypothesis"}

PM_ACTIONS = {
    "open_center",
    "add_on",
    "reduce_add_on",
    "reduce_center",
    "inventory_seed",
    "lock_candidate",
    "unlock",
    "rebalance",
    "clear",
    "hold",
}

METHOD_ACTION_CATALOG = {
    "trend_probe_entry": {
        "layer": "method",
        "pm_required_default": False,
        "execution_replay_allowed": True,
        "malf_can_generate": False,
        "boundary_warning": ["method_action_requires_method_evidence_not_malf_only"],
    },
    "trend_confirmation_add": {
        "layer": "method",
        "pm_required_default": True,
        "execution_replay_allowed": True,
        "malf_can_generate": False,
        "boundary_warning": ["do_not_treat_addon_as_malf_structure_strength"],
    },
    "pullback_entry": {
        "layer": "method",
        "pm_required_default": True,
        "execution_replay_allowed": True,
        "malf_can_generate": False,
        "boundary_warning": ["pullback_entry_requires_method_context"],
    },
    "pullback_add": {
        "layer": "method",
        "pm_required_default": True,
        "execution_replay_allowed": True,
        "malf_can_generate": False,
        "boundary_warning": ["pullback_add_requires_pm_context"],
    },
    "distribution_reduce": {
        "layer": "method",
        "pm_required_default": True,
        "execution_replay_allowed": True,
        "malf_can_generate": False,
        "boundary_warning": ["do_not_infer_reduce_reason_from_malf"],
    },
    "exit_on_rhythm_failure": {
        "layer": "method",
        "pm_required_default": True,
        "execution_replay_allowed": True,
        "malf_can_generate": False,
        "boundary_warning": ["do_not_encode_accept_loss_in_malf"],
    },
    "reversal_flip": {
        "layer": "method",
        "pm_required_default": True,
        "execution_replay_allowed": True,
        "malf_can_generate": False,
        "boundary_warning": ["do_not_treat_reversal_as_malf_decision"],
    },
    "inventory_rebalance": {
        "layer": "method",
        "pm_required_default": True,
        "execution_replay_allowed": True,
        "malf_can_generate": False,
        "boundary_warning": ["inventory_rebalance_requires_pm_context"],
    },
    "wait_no_action": {
        "layer": "method",
        "pm_required_default": False,
        "execution_replay_allowed": False,
        "malf_can_generate": False,
        "boundary_warning": ["do_not_infer_wait_reason_from_malf_only"],
    },
}

PM_ACTION_CATALOG = {
    "open_center": {
        "layer": "pm",
        "state_mutation": True,
        "malf_can_generate": False,
        "boundary_warning": ["do_not_infer_center_position_from_malf"],
    },
    "add_on": {
        "layer": "pm",
        "state_mutation": True,
        "malf_can_generate": False,
        "boundary_warning": ["do_not_treat_addon_size_as_structure_fact"],
    },
    "reduce_add_on": {
        "layer": "pm",
        "state_mutation": True,
        "malf_can_generate": False,
        "boundary_warning": ["do_not_encode_profit_or_loss_reason_in_malf"],
    },
    "reduce_center": {
        "layer": "pm",
        "state_mutation": True,
        "malf_can_generate": False,
        "boundary_warning": ["center_reduction_requires_pm_evidence"],
    },
    "inventory_seed": {
        "layer": "pm",
        "state_mutation": True,
        "malf_can_generate": False,
        "boundary_warning": ["do_not_merge_inventory_seed_into_old_segment"],
    },
    "lock_candidate": {
        "layer": "pm",
        "state_mutation": True,
        "malf_can_generate": False,
        "boundary_warning": ["do_not_confirm_lock_from_dual_inventory_only"],
    },
    "unlock": {
        "layer": "pm",
        "state_mutation": True,
        "malf_can_generate": False,
        "boundary_warning": ["do_not_write_unlock_into_malf"],
    },
    "rebalance": {
        "layer": "pm",
        "state_mutation": True,
        "malf_can_generate": False,
        "boundary_warning": ["rebalance_requires_pm_ledger"],
    },
    "clear": {
        "layer": "pm",
        "state_mutation": True,
        "malf_can_generate": False,
        "boundary_warning": ["do_not_encode_clear_reason_in_malf"],
    },
    "hold": {
        "layer": "pm",
        "state_mutation": False,
        "malf_can_generate": False,
        "boundary_warning": ["hold_reason_requires_method_or_pm_context"],
    },
}

METHOD_PM_FORBIDDEN_FIELDS = {
    "buy_signal",
    "sell_signal",
    "trade_accept",
    "target_position",
    "position_size",
    "center_position_from_malf",
    "target_position_from_malf",
    "lock_confirmed_by_malf",
}

METHOD_PM_BRIDGE_GATE_FIELDS = [
    "method_action",
    "method_status",
    "method_reason",
    "pm_required",
    "pm_action",
    "execution_intent",
    "execution_event_type",
]

INTERFACE_BOUNDARY_GATE_FIELDS = [
    "interface_layer",
    "rhythm_meaning",
    "tachibana_applicability",
    "method_action",
    "pm_action",
    "execution_intent",
]

RHYTHM_SAMPLE_ROW_GATE_FIELDS = [
    "sample_id",
    "source_scope",
    "snapshot_quality_status",
    "malf_background",
    "qualification_rule_id",
    "rhythm_meaning",
    "tachibana_applicability",
    "pm_complexity",
    "meaning_reason",
    "boundary_warning",
    "evidence_level",
]

COGNITIVE_PIPELINE_GATE_FIELDS = [
    "front_filter_system_audit",
    "contract_check_result",
    "eligible_for_malf_run",
    "malf_snapshot_ref",
    "snapshot_quality_status",
    "rhythm_meaning",
    "tachibana_applicability",
    "candidate_table_gate",
    "rhythm_sample_row_gate",
    "method_pm_bridge_gate",
    "interface_boundary_gate",
    "backtest_input_gate",
    "institution_constraint_need",
]

DATA_LAYER_FORBIDDEN_FIELDS = {
    "rhythm_meaning",
    "tachibana_applicability",
    "method_action",
    "pm_action",
    "target_position",
    "trade_accept",
    "signal_decision",
}

SIGNAL_LAYER_FORBIDDEN_FIELDS = {
    "rhythm_meaning",
    "tachibana_applicability",
    "method_action",
    "pm_action",
    "signal_decision_from_rhythm",
    "trade_accept_from_meaningful",
    "trade_reject_from_not_meaningful",
}

BACKTEST_LAYER_FORBIDDEN_WRITES = {
    "rhythm_meaning",
    "tachibana_applicability",
    "structure_suitable",
    "qualification_rule_id",
    "malf_background",
}

INTERFACE_BOUNDARY_CATALOG = {
    "data": {
        "layer": "data",
        "may_read_structure_qualification": False,
        "may_write_structure_qualification": False,
        "may_write_trade_decision": False,
        "forbidden_fields": sorted(DATA_LAYER_FORBIDDEN_FIELDS),
        "boundary_warning": ["data_layer_must_remain_fact_only"],
    },
    "signal": {
        "layer": "signal",
        "may_read_structure_qualification": False,
        "may_write_structure_qualification": False,
        "may_write_trade_decision": False,
        "forbidden_fields": sorted(SIGNAL_LAYER_FORBIDDEN_FIELDS),
        "boundary_warning": ["signal_layer_must_not_front_run_structure_qualification"],
    },
    "backtest": {
        "layer": "backtest",
        "may_read_structure_qualification": True,
        "may_write_structure_qualification": False,
        "may_write_trade_decision": False,
        "forbidden_fields": sorted(BACKTEST_LAYER_FORBIDDEN_WRITES),
        "boundary_warning": ["backtest_layer_consumes_adapter_output_only"],
    },
    "tachibana_adapter": {
        "layer": "tachibana_adapter",
        "may_read_structure_qualification": True,
        "may_write_structure_qualification": True,
        "may_write_trade_decision": False,
        "forbidden_fields": sorted(BACKTEST_INPUT_FORBIDDEN_FIELDS),
        "boundary_warning": ["adapter_writes_structure_qualification_not_trade_decision"],
    },
}

PM_COMPLEXITY_VALUES = {"none", "low", "medium", "high"}
RHYTHM_MEANING_VALUES = {"meaningful", "limited", "not_meaningful", "unknown"}
APPPLICABILITY_BY_RHYTHM = {
    "meaningful": "suitable",
    "limited": "conditional",
    "not_meaningful": "unsuitable",
    "unknown": "unknown",
}
MINIMUM_SAMPLE_COUNT_BY_RHYTHM_MEANING = {
    "meaningful": 2,
    "limited": 2,
    "not_meaningful": 2,
    "unknown": 2,
}
LIMITED_REQUIRED_RULES = {
    "Q-ALIVE-PM-MIXED",
    "Q-EXTREME-ADDON",
    "Q-PRESSURE-ADJUST",
    "Q-REDUCE-WINDOW",
    "Q-NO-TRADE",
    "Q-LOCK-WAIT",
    "Q-SEED-AFTER-CLEAR",
    "Q-CLEAR-RESET",
    "Q-LOCK-CANDIDATE",
    "Q-UNLOCK",
    "Q-SOURCE-DISRUPTED",
}
NOT_MEANINGFUL_RULES = {
    "NM-NO-STRUCTURE",
    "NM-NO-RHYTHM-OBJECT",
    "NM-NOISE-DOMINATED",
    "NM-EVENT-DOMINATED",
}

QUALIFICATION_RULE_CATALOG = {
    "Q-ALIVE-CLEAN": {
        "rhythm_meaning": "meaningful",
        "tachibana_applicability": "suitable",
        "pm_complexity": "none",
        "pm_required": False,
        "candidate_stage_after": "tachibana_candidate",
        "rule_family": "positive",
        "boundary_warning": [
            "do_not_infer_position_size_from_malf",
            "do_not_convert_rhythm_meaning_to_signal_accept",
        ],
    },
    "Q-ALIVE-PM-MIXED": {
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "medium",
        "pm_required": True,
        "candidate_stage_after": "tachibana_candidate",
        "rule_family": "limited",
        "boundary_warning": ["do_not_write_center_or_inventory_state_into_malf"],
    },
    "Q-SEED-AFTER-CLEAR": {
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "high",
        "pm_required": True,
        "candidate_stage_after": "tachibana_candidate",
        "rule_family": "limited",
        "boundary_warning": ["do_not_merge_new_seed_into_old_segment"],
    },
    "Q-EXTREME-ADDON": {
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "high",
        "pm_required": True,
        "candidate_stage_after": "tachibana_candidate",
        "rule_family": "limited",
        "boundary_warning": ["do_not_treat_large_addon_as_structure_fact"],
    },
    "Q-PRESSURE-ADJUST": {
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "medium",
        "pm_required": True,
        "candidate_stage_after": "tachibana_candidate",
        "rule_family": "limited",
        "boundary_warning": ["do_not_merge_pressure_adjustment_into_clean_wave"],
    },
    "Q-REDUCE-WINDOW": {
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "medium",
        "pm_required": True,
        "candidate_stage_after": "tachibana_candidate",
        "rule_family": "limited",
        "boundary_warning": ["do_not_infer_profit_or_loss_reason_from_reduce_only"],
    },
    "Q-NO-TRADE": {
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "low",
        "pm_required": False,
        "candidate_stage_after": "tachibana_candidate",
        "rule_family": "limited",
        "boundary_warning": ["do_not_infer_range_from_no_trade"],
    },
    "Q-LOCK-WAIT": {
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "medium",
        "pm_required": True,
        "candidate_stage_after": "tachibana_candidate",
        "rule_family": "limited",
        "boundary_warning": ["do_not_infer_range_from_no_trade"],
    },
    "Q-CLEAR-RESET": {
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "high",
        "pm_required": True,
        "candidate_stage_after": "tachibana_candidate",
        "rule_family": "limited",
        "boundary_warning": ["do_not_encode_clear_reason_in_malf"],
    },
    "Q-LOCK-CANDIDATE": {
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "high",
        "pm_required": True,
        "candidate_stage_after": "tachibana_candidate",
        "rule_family": "limited",
        "boundary_warning": ["do_not_confirm_lock_from_dual_inventory_only"],
    },
    "Q-UNLOCK": {
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "high",
        "pm_required": True,
        "candidate_stage_after": "tachibana_candidate",
        "rule_family": "limited",
        "boundary_warning": ["do_not_write_unlock_into_malf"],
    },
    "Q-SOURCE-DISRUPTED": {
        "rhythm_meaning": "unknown",
        "tachibana_applicability": "unknown",
        "pm_complexity": "high",
        "pm_required": False,
        "candidate_stage_after": "structure_candidate",
        "rule_family": "blocked",
        "boundary_warning": ["source_disrupted_keep_unknown"],
    },
    "NM-NO-STRUCTURE": {
        "rhythm_meaning": "not_meaningful",
        "tachibana_applicability": "unsuitable",
        "pm_complexity": "none",
        "pm_required": False,
        "candidate_stage_after": "rejected",
        "rule_family": "negative",
        "boundary_warning": ["do_not_apply_tachibana_without_structure_object"],
    },
    "NM-NO-RHYTHM-OBJECT": {
        "rhythm_meaning": "not_meaningful",
        "tachibana_applicability": "unsuitable",
        "pm_complexity": "none",
        "pm_required": False,
        "candidate_stage_after": "rejected",
        "rule_family": "negative",
        "boundary_warning": ["do_not_apply_tachibana_without_rhythm_object"],
    },
    "NM-NOISE-DOMINATED": {
        "rhythm_meaning": "not_meaningful",
        "tachibana_applicability": "unsuitable",
        "pm_complexity": "none",
        "pm_required": False,
        "candidate_stage_after": "rejected",
        "rule_family": "negative",
        "boundary_warning": ["do_not_extract_tachibana_rhythm_from_noise"],
    },
    "NM-EVENT-DOMINATED": {
        "rhythm_meaning": "not_meaningful",
        "tachibana_applicability": "unsuitable",
        "pm_complexity": "none",
        "pm_required": False,
        "candidate_stage_after": "rejected",
        "rule_family": "negative",
        "boundary_warning": ["do_not_replace_structure_qualification_with_event_reason"],
    },
}

RHYTHM_SAMPLE_CATALOG = {
    "1975-01": {
        "sample_id": "1975-01",
        "source_scope": "historical_review",
        "source_anchor": "docs/tachibana/monthly/1975-01.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": None,
        "malf_background": "alive_wave",
        "qualification_rule_id": "Q-ALIVE-CLEAN",
        "rhythm_meaning": "meaningful",
        "tachibana_applicability": "suitable",
        "pm_complexity": "none",
        "pm_required": False,
        "meaning_reason": ["structure_clean_alive_wave", "rhythm_meaning_meaningful"],
        "boundary_warning": [
            "do_not_infer_position_size_from_malf",
            "do_not_convert_rhythm_meaning_to_signal_accept",
        ],
        "evidence_level": ["E4_research_mapping"],
    },
    "1975-02": {
        "sample_id": "1975-02",
        "source_scope": "historical_review",
        "source_anchor": "docs/tachibana/monthly/1975-02.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": None,
        "malf_background": "alive_wave",
        "qualification_rule_id": "Q-ALIVE-CLEAN",
        "rhythm_meaning": "meaningful",
        "tachibana_applicability": "suitable",
        "pm_complexity": "none",
        "pm_required": False,
        "meaning_reason": ["structure_clean_alive_wave", "rhythm_meaning_meaningful"],
        "boundary_warning": [
            "do_not_infer_position_size_from_malf",
            "do_not_convert_rhythm_meaning_to_signal_accept",
        ],
        "evidence_level": ["E4_research_mapping"],
    },
    "RULE-SAMPLE-Q-ALIVE-PM-MIXED": {
        "sample_id": "RULE-SAMPLE-Q-ALIVE-PM-MIXED",
        "source_scope": "synthetic_rule_fixture",
        "source_anchor": "docs/tachibana/index/MALF-立花结构状态到仓位节奏意义判定准则-v0.1.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": "fixture:not-real",
        "malf_background": "alive_wave",
        "qualification_rule_id": "Q-ALIVE-PM-MIXED",
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "medium",
        "pm_required": True,
        "meaning_reason": ["alive_wave_pm_mixed", "rhythm_meaning_limited"],
        "boundary_warning": ["do_not_write_center_or_inventory_state_into_malf"],
        "evidence_level": ["E4_research_mapping"],
    },
    "RULE-SAMPLE-Q-SEED-AFTER-CLEAR": {
        "sample_id": "RULE-SAMPLE-Q-SEED-AFTER-CLEAR",
        "source_scope": "historical_review",
        "source_anchor": "docs/tachibana/index/MALF-立花1976-03与07交易段结构资格审计-v0.1.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": None,
        "malf_background": "break_birth",
        "qualification_rule_id": "Q-SEED-AFTER-CLEAR",
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "high",
        "pm_required": True,
        "meaning_reason": ["seed_after_clear_new_segment", "rhythm_meaning_limited"],
        "boundary_warning": ["do_not_merge_new_seed_into_old_segment"],
        "evidence_level": ["E2_trade_fact", "E4_research_mapping"],
    },
    "1976-11-A": {
        "sample_id": "1976-11-A",
        "source_scope": "historical_review",
        "source_anchor": "docs/tachibana/index/MALF-立花1976-11交易段结构资格审计-v0.1.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": None,
        "malf_background": "alive_wave",
        "qualification_rule_id": "Q-EXTREME-ADDON",
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "high",
        "pm_required": True,
        "meaning_reason": ["extreme_addon_pm_dominant", "rhythm_meaning_limited"],
        "boundary_warning": ["do_not_treat_large_addon_as_structure_fact"],
        "evidence_level": ["E2_trade_fact", "E4_research_mapping"],
    },
    "RULE-SAMPLE-Q-PRESSURE-ADJUST": {
        "sample_id": "RULE-SAMPLE-Q-PRESSURE-ADJUST",
        "source_scope": "historical_review",
        "source_anchor": "docs/tachibana/index/MALF-立花1976-03与07交易段结构资格审计-v0.1.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": None,
        "malf_background": "pullback",
        "qualification_rule_id": "Q-PRESSURE-ADJUST",
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "medium",
        "pm_required": True,
        "meaning_reason": ["pressure_adjustment_pm_required", "rhythm_meaning_limited"],
        "boundary_warning": ["do_not_merge_pressure_adjustment_into_clean_wave"],
        "evidence_level": ["E2_trade_fact", "E4_research_mapping"],
    },
    "RULE-SAMPLE-Q-REDUCE-WINDOW": {
        "sample_id": "RULE-SAMPLE-Q-REDUCE-WINDOW",
        "source_scope": "historical_review",
        "source_anchor": "docs/tachibana/index/MALF-立花1976-03与07交易段结构资格审计-v0.1.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": None,
        "malf_background": "stagnation",
        "qualification_rule_id": "Q-REDUCE-WINDOW",
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "medium",
        "pm_required": True,
        "meaning_reason": ["reduce_window_pm_required", "rhythm_meaning_limited"],
        "boundary_warning": ["do_not_infer_profit_or_loss_reason_from_reduce_only"],
        "evidence_level": ["E2_trade_fact", "E4_research_mapping"],
    },
    "RULE-SAMPLE-Q-NO-TRADE": {
        "sample_id": "RULE-SAMPLE-Q-NO-TRADE",
        "source_scope": "historical_review",
        "source_anchor": "docs/tachibana/monthly/1975-08.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": None,
        "malf_background": "range",
        "qualification_rule_id": "Q-NO-TRADE",
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "low",
        "pm_required": False,
        "meaning_reason": ["no_trade_waiting_only", "rhythm_meaning_limited"],
        "boundary_warning": ["do_not_infer_range_from_no_trade"],
        "evidence_level": ["E4_research_mapping"],
    },
    "RULE-SAMPLE-Q-LOCK-WAIT": {
        "sample_id": "RULE-SAMPLE-Q-LOCK-WAIT",
        "source_scope": "historical_review",
        "source_anchor": "docs/tachibana/index/MALF-立花1976-04至05交易段结构资格审计-v0.1.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": None,
        "malf_background": "range",
        "qualification_rule_id": "Q-LOCK-WAIT",
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "medium",
        "pm_required": True,
        "meaning_reason": ["lock_wait_pm_required", "rhythm_meaning_limited"],
        "boundary_warning": ["do_not_infer_range_from_no_trade"],
        "evidence_level": ["E2_trade_fact", "E4_research_mapping"],
    },
    "RULE-SAMPLE-Q-CLEAR-RESET": {
        "sample_id": "RULE-SAMPLE-Q-CLEAR-RESET",
        "source_scope": "historical_review",
        "source_anchor": "docs/tachibana/index/MALF-立花1976-03与07交易段结构资格审计-v0.1.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": None,
        "malf_background": "stagnation",
        "qualification_rule_id": "Q-CLEAR-RESET",
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "high",
        "pm_required": True,
        "meaning_reason": ["clear_reset_pm_required", "rhythm_meaning_limited"],
        "boundary_warning": ["do_not_encode_clear_reason_in_malf"],
        "evidence_level": ["E2_trade_fact", "E4_research_mapping"],
    },
    "RULE-SAMPLE-Q-LOCK-CANDIDATE": {
        "sample_id": "RULE-SAMPLE-Q-LOCK-CANDIDATE",
        "source_scope": "historical_review",
        "source_anchor": "docs/tachibana/index/MALF-立花1976-04至05交易段结构资格审计-v0.1.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": None,
        "malf_background": "transition",
        "qualification_rule_id": "Q-LOCK-CANDIDATE",
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "high",
        "pm_required": True,
        "meaning_reason": ["lock_candidate_dual_inventory", "rhythm_meaning_limited"],
        "boundary_warning": ["do_not_confirm_lock_from_dual_inventory_only"],
        "evidence_level": ["E2_trade_fact", "E4_research_mapping"],
    },
    "RULE-SAMPLE-Q-UNLOCK": {
        "sample_id": "RULE-SAMPLE-Q-UNLOCK",
        "source_scope": "historical_review",
        "source_anchor": "docs/tachibana/index/MALF-立花1976-04至05交易段结构资格审计-v0.1.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": None,
        "malf_background": "transition",
        "qualification_rule_id": "Q-UNLOCK",
        "rhythm_meaning": "limited",
        "tachibana_applicability": "conditional",
        "pm_complexity": "high",
        "pm_required": True,
        "meaning_reason": ["unlock_pm_event", "rhythm_meaning_limited"],
        "boundary_warning": ["do_not_write_unlock_into_malf"],
        "evidence_level": ["E2_trade_fact", "E4_research_mapping"],
    },
    "1976-09": {
        "sample_id": "1976-09",
        "source_scope": "historical_review",
        "source_anchor": "docs/tachibana/index/MALF-立花1976-09制度资料口径审计-v0.1.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": None,
        "malf_background": "unknown",
        "qualification_rule_id": "Q-SOURCE-DISRUPTED",
        "rhythm_meaning": "unknown",
        "tachibana_applicability": "unknown",
        "pm_complexity": "high",
        "pm_required": False,
        "meaning_reason": ["source_disrupted_keep_unknown", "rhythm_meaning_unknown"],
        "boundary_warning": ["do_not_mix_unit_change_ex_rights_and_structure_qualification"],
        "evidence_level": ["E2_trade_fact", "E3_source_audit"],
    },
    "RULE-SAMPLE-Q-SOURCE-DISRUPTED-FIXTURE": {
        "sample_id": "RULE-SAMPLE-Q-SOURCE-DISRUPTED-FIXTURE",
        "source_scope": "synthetic_rule_fixture",
        "source_anchor": "docs/tachibana/index/MALF-立花1976-09制度资料口径审计-v0.1.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": "fixture:not-real",
        "malf_background": "unknown",
        "qualification_rule_id": "Q-SOURCE-DISRUPTED",
        "rhythm_meaning": "unknown",
        "tachibana_applicability": "unknown",
        "pm_complexity": "high",
        "pm_required": False,
        "meaning_reason": ["source_disrupted_keep_unknown", "rhythm_meaning_unknown"],
        "boundary_warning": ["source_disrupted_keep_unknown"],
        "evidence_level": ["E3_source_audit", "E4_research_mapping"],
    },
    "NM-NO-STRUCTURE-FIXTURE": {
        "sample_id": "NM-NO-STRUCTURE-FIXTURE",
        "source_scope": "synthetic_test_fixture",
        "source_anchor": "docs/tachibana/index/MALF-立花not_meaningful反例登记表-v0.1.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": "fixture:not-real",
        "malf_background": "no_structure",
        "qualification_rule_id": "NM-NO-STRUCTURE",
        "rhythm_meaning": "not_meaningful",
        "tachibana_applicability": "unsuitable",
        "pm_complexity": "none",
        "pm_required": False,
        "meaning_reason": ["negative_type_nm_no_structure", "rhythm_meaning_not_meaningful"],
        "boundary_warning": ["do_not_apply_tachibana_without_structure_object"],
        "evidence_level": ["E1_malf_snapshot", "E4_research_mapping"],
    },
    "RULE-SAMPLE-NM-NO-RHYTHM-OBJECT": {
        "sample_id": "RULE-SAMPLE-NM-NO-RHYTHM-OBJECT",
        "source_scope": "synthetic_test_fixture",
        "source_anchor": "docs/tachibana/index/MALF-立花not_meaningful反例登记表-v0.1.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": "fixture:not-real",
        "malf_background": "no_rhythm_object",
        "qualification_rule_id": "NM-NO-RHYTHM-OBJECT",
        "rhythm_meaning": "not_meaningful",
        "tachibana_applicability": "unsuitable",
        "pm_complexity": "none",
        "pm_required": False,
        "meaning_reason": ["no_tachibana_rhythm_object", "rhythm_meaning_not_meaningful"],
        "boundary_warning": ["do_not_apply_tachibana_without_rhythm_object"],
        "evidence_level": ["E1_malf_snapshot", "E4_research_mapping"],
    },
    "RULE-SAMPLE-NM-NOISE-DOMINATED": {
        "sample_id": "RULE-SAMPLE-NM-NOISE-DOMINATED",
        "source_scope": "synthetic_test_fixture",
        "source_anchor": "docs/tachibana/index/MALF-立花not_meaningful反例登记表-v0.1.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": "fixture:not-real",
        "malf_background": "noise_dominated",
        "qualification_rule_id": "NM-NOISE-DOMINATED",
        "rhythm_meaning": "not_meaningful",
        "tachibana_applicability": "unsuitable",
        "pm_complexity": "none",
        "pm_required": False,
        "meaning_reason": ["noise_dominated_no_rhythm", "rhythm_meaning_not_meaningful"],
        "boundary_warning": ["do_not_extract_tachibana_rhythm_from_noise"],
        "evidence_level": ["E1_malf_snapshot", "E4_research_mapping"],
    },
    "RULE-SAMPLE-NM-EVENT-DOMINATED": {
        "sample_id": "RULE-SAMPLE-NM-EVENT-DOMINATED",
        "source_scope": "synthetic_test_fixture",
        "source_anchor": "docs/tachibana/index/MALF-立花not_meaningful反例登记表-v0.1.md",
        "snapshot_quality_status": "ready",
        "malf_snapshot_ref": "fixture:not-real",
        "malf_background": "event_dominated",
        "qualification_rule_id": "NM-EVENT-DOMINATED",
        "rhythm_meaning": "not_meaningful",
        "tachibana_applicability": "unsuitable",
        "pm_complexity": "none",
        "pm_required": False,
        "meaning_reason": ["event_dominated_no_structure_qualification", "rhythm_meaning_not_meaningful"],
        "boundary_warning": ["do_not_replace_structure_qualification_with_event_reason"],
        "evidence_level": ["E1_malf_snapshot", "E4_research_mapping"],
    },
}

BACKTEST_INPUT_GATE_FIELDS = [
    "candidate_table_gate",
    "method_pm_bridge_gate",
    "rhythm_meaning",
    "tachibana_applicability",
    "qualification_rule_id",
    "boundary_warning",
    "evidence_level",
    "method_action",
    "method_status",
    "method_reason",
    "pm_required",
    "pm_action",
    "execution_intent",
    "execution_event_type",
]


def get_qualification_rule_catalog() -> dict[str, dict[str, Any]]:
    return json.loads(json.dumps(QUALIFICATION_RULE_CATALOG))


def get_method_action_catalog() -> dict[str, dict[str, Any]]:
    return json.loads(json.dumps(METHOD_ACTION_CATALOG))


def get_pm_action_catalog() -> dict[str, dict[str, Any]]:
    return json.loads(json.dumps(PM_ACTION_CATALOG))


def get_interface_boundary_catalog() -> dict[str, dict[str, Any]]:
    return json.loads(json.dumps(INTERFACE_BOUNDARY_CATALOG))


def get_rhythm_sample_catalog() -> dict[str, dict[str, Any]]:
    return json.loads(json.dumps(RHYTHM_SAMPLE_CATALOG))
